
const mongoose = require('mongoose');

// This 3rd Comment table is generated by User & Post tables:
const CommentSchema = new mongoose.Schema({
    user_id: { type: Integer,
        required: [true, "A user is required to make a comment."]
    },
    post_id: { type: Integer,
        required: [true, "A post is required to make a comment."]
    },
    message: { type: String,
            required: [true, "Message is required to write a comment."]
     }
}, 
    { timestamps: true }
);
module.exports.Comment = mongoose.model('Comment', CommentSchema);